apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
      version: v1
  template:
    metadata:
      labels:
        app: demoapp
        version: v1
        prueba: beta0
    spec:
      containers:
      - name: demoapp
        image: tuxotron/demoapp:v1
        ports:
        - containerPort: 8080


