apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
      version: v2
  template:
    metadata:
      labels:
        app: demoapp
        version: v2
        prueba: beta1
    spec:
      containers:
      - name: demoapp
        image: tuxotron/demoapp:v2
        ports:
        - containerPort: 8080
        